#端口配置
server:
  port: 8081
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: false
#    check-template-location：false
mybatis:
  configuration:
    map-underscore-to-camel-case=true:

winResource: D:\testFile

logging:
  level:
    com.system.dao : debug